<?php

namespace Database\Factories;

use App\Models\GpsLocation;
use App\Models\Trip;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * The PostGIS `location` column is derived automatically from latitude/longitude
 * (App\Models\Concerns\HasLocationPoint); `id` is generated by HasUuids.
 *
 * @extends Factory<GpsLocation>
 */
class GpsLocationFactory extends Factory
{
    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'trip_id' => Trip::factory(),
            'latitude' => fake()->latitude(9.8, 10.1),
            'longitude' => fake()->longitude(-84.2, -83.9),
            'speed_kmh' => fake()->randomFloat(2, 0, 80),
            'recorded_at' => now(),
        ];
    }
}
